#ifndef CONSTANTS_H
#define CONSTANTS_H

const short CATEGORY_KERNEL = 0x0001;
const short CATEGORY_ATOM = 0x0002;
const short CATEGORY_ATOM_VIRTUAL = 0x0004;
const short MASK_ATOMS = CATEGORY_KERNEL | CATEGORY_ATOM | CATEGORY_ATOM_VIRTUAL;

const float WORLD_FIXED_WIDTH = 1280;
const float WORLD_FIXED_HEIGHT = 800;
const float WORLD_SCALE = 250.0;


enum {
    MEASURE_CORRECTION,
    MEASURE_EMPTY,
    MEASURE_ADD_SNIPPET_0,
    MEASURE_ADD_SNIPPET_1,
    MEASURE_GROW_NORMAL_0,
    MEASURE_GROW_NORMAL_1,
    MEASURE_GROW_NORMAL_2,
    MEASURE_GROW_NORMALS,
    MEASURE_UPDATE_RADIAL,
    MEASURE_UPDATE_TANGEN,
    MEASURE_UPDATE_TANGEN_0,
    MEASURE_UPDATE_TANGEN_1,
    MEASURE_UPDATE_TANGEN_2,
    MEASURE_UPDATE_TANGEN_3,
    MEASURE_UPDATE_TANGEN_4,
    MEASURE_GENERATE_GEOMETRY,
    MEASURE_FILL_SECTORS,
    MEASURE_UPDATE_WORLD_VIEW,
    MEASURE_UPDATE_CONTROLLER,
    MEASURE_BEZIER_POINTS,
};

#endif // CONSTANTS_H
